name: Checks for new tags and publishes them

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  check-for-new-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Publish new tags
        run: ./check-tags.sh
