name: Checks for new tags and publishes them

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  check-for-new-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish new tags
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: ./check-tags.sh
